### PR TITLE
Added Jenkins

### PR DESCRIPTION
**Pull request by richardjh**

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thanks @richardjh :+1:

**Comment by richardjh** [comment]
@eddiejaoude I was considering adding blade and eloquent added to templates and ORMs resp. but they aren't commonly used outside laravel, so I didn't. Thoughts?

**Comment by eddiejaoude** [comment]
Hmm thats a tough one.

We could have a **laravel** page & then under a sub section list them there?

**Comment by richardjh** [comment]
Lets leave it then. Laravel devs know about them and people not using Laravel are unlikely to use them outside the framework.

**Comment by eddiejaoude** [comment]
Yep, makes sense :smile:

**Pull request merged**
